### ISSUE TITLE
more responsive and smooth audio visualization

### ISSUE THREAD

**Issue by nikjetchev** [blythed/ailive#2]
https://github.com/blythed/ailive/blob/ba5caf0d79be7290f7d3847003a6ae5a9373711d/ailive/animate.py#L145

add to the very first line of the infer function:

`x=x[:,-1:]`

this should make the code more responsive by using the latest audio buffer only

In addition, the normalization code on line 145 is wrong anyway when using multiple time steps:

it should become

x = self.normalizer * x / (x.sum(0) + 0.0001)  + (1 - self.normalizer) * x

I hope you have enough time to take a look and fix this before Thursday, can really help a lot. I tested it yesterday at home and works great.

**Comment by nikjetchev** [comment]
But the first change is more important, the normalizer change does not matter so much if we only have 1 buffer step with x=x[:,-1:]

**Comment by blythed** [comment]
Yes that really speeds up the response, thanks!
